apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.name }}-secret
data:
  username: {{ .Values.minio.username | b64enc | quote }}
  password: {{ .Values.minio.password | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.name }}-secret
data:
  username: {{ .Values.mongo.username | b64enc | quote }}
  password: {{ .Values.mongo.password | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.orthanc.name }}-secret
data:
  users: {{ "{\"{{ .Values.orthanc.username  }} \":\"{{ .Values.orthanc.password  }} \"}"  | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.name }}-secret
data:
  username: {{ .Values.rabbitmq.username | b64enc | quote }}
  password: {{ .Values.rabbitmq.password | b64enc | quote }}


---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.name }}-secret
data:
  username: {{ .Values.postgres.username | b64enc | quote }}
  password: {{ .Values.postgres.password | b64enc | quote }}