
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ .Release.Namespace }}
  name: pods-patch-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: pods-patch-role-binding
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: default
roleRef:
 kind: ClusterRole
 name: pods-patch-role
 apiGroup: rbac.authorization.k8s.io

---

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "local.serviceAccountName" . }}
  labels:
    {{- include "local.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: {{ include "local.serviceAccountName" . }}-Role-Secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: {{ include "local.serviceAccountName" . }}-RoleBinding-Secrets
subjects:
- kind: ServiceAccount
  name: {{ include "local.serviceAccountName" . }}
roleRef:
 kind: Role
 name: {{ include "local.serviceAccountName" . }}-Role-Secrets
 apiGroup: rbac.authorization.k8s.io
{{- end }}

---
