apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Values.orthanc.name }}-volume
  labels:
    type: local
spec:
  storageClassName: {{ .Release.Name }}-{{ .Values.orthanc.name }}-volume-class
  capacity:
    storage: {{ .Values.orthanc.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.orthanc.storagePath }}
    type: "DirectoryOrCreate"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.orthanc.name }}-volume-claim
spec:
  storageClassName: {{ .Release.Name }}-{{ .Values.orthanc.name }}-volume-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.orthanc.size }}