apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mig.serviceName }}
  labels:
    {{- include "local.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mig.serviceType }}
  ports:
    - name: dimse
      port: 104
      nodePort: {{ .Values.mig.dimsePort }}
      targetPort: dimse-port
      protocol: TCP
    - name: mig-api
      port: 5000
      nodePort: {{ .Values.mig.apiPort }}
      targetPort: mig-api-port
      protocol: TCP
  selector:
    role: external-svcs
    {{- include "local.selectorLabels" . | nindent 4 }}
