# MIG log volume and volume claim
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Values.mig.name }}-log-volume
  labels:
    type: local
spec:
  storageClassName: {{ .Release.Name }}-{{ .Values.mig.name }}-log-volume-class
  capacity:
    storage: {{ .Values.mig.logsSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mig.storagePath }}
    type: "DirectoryOrCreate"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.mig.name }}-logs-volume-claim
spec:
  storageClassName: {{ .Release.Name }}-{{ .Values.mig.name }}-log-volume-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mig.logsSize }}
---
# MIG payloads volume and volume claim
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Values.mig.name }}-payloads-volume
  labels:
    type: local
spec:
  storageClassName: {{ .Release.Name }}-{{ .Values.mig.name }}-payloads-volume-class
  capacity:
    storage: {{ .Values.mig.payloadSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mig.storagePath }}
    type: "DirectoryOrCreate"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.mig.name }}-payloads-volume-claim
spec:
  storageClassName: {{ .Release.Name }}-{{ .Values.mig.name }}-payloads-volume-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mig.payloadSize }}