apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mtm.serviceName }}
  labels:
    {{- include "local.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mtm.serviceType }}
  ports:
    - port: {{ .Values.mtm.apiPort }}
      targetPort: mtm-api-port
      protocol: TCP
      name: mtm-api
  selector:
    role: external-svcs
    {{- include "local.selectorLabels" . | nindent 4 }}
