# kind: NetworkPolicy
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: {{ .Values.mig.serviceName }}-policy
# spec:
#   podSelector:
#     matchLabels:
#       role: internal-svcs
#   ingress:
#     - from:
#         - namespaceSelector:
#             matchLabels:
#               role: external-svcs
#       ports:
#         - protocol: TCP
#           port: {{ .Values.mongo.port }}